name: Annotations from Rubocop Output Action
description: GitHub Action for creating annotations from json RuboCop results file. Annotations are created for error, warning, and convention offenses.
author: "Ashley Engelund <ashley.engelund@gmail.com>"
branding:
  icon: alert-triangle
  color: purple
inputs:
  path:
    required: true
    description: path to RuboCop results JSON file
    default: rubocop.json
runs:
  using: node12
  main: dist/index.js
